# Generated by Django 2.2.9 on 2020-06-29 12:29

import accounts.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200629_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='name',
        ),
        migrations.AddField(
            model_name='emergency',
            name='location',
            field=djongo.models.fields.EmbeddedModelField(model_container=accounts.models.Locations, model_form_class=accounts.models.LocationsForm, null=True),
        ),
    ]
