# Generated by Django 2.2.9 on 2020-06-29 19:27

import accounts.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200629_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Primary_Fenders', models.CharField(blank=True, max_length=1000, null=True)),
                ('Secondary_Fenders', models.CharField(blank=True, max_length=1000, null=True)),
                ('Fender_Moorings', models.CharField(blank=True, max_length=1000, null=True)),
                ('Rubber_Hoses', models.CharField(blank=True, max_length=1000, null=True)),
                ('Composite_Hoses', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='equipment_details',
            field=djongo.models.fields.EmbeddedModelField(model_container=accounts.models.Equipment_Details, model_form_class=accounts.models.Equipment_DetailsForm, null=True),
        ),
    ]
