# Generated by Django 2.2.9 on 2020-06-29 19:36

import accounts.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200629_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notice_Period', models.CharField(blank=True, max_length=1000, null=True)),
                ('Documentation_Requirements', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='notice_period',
            field=djongo.models.fields.EmbeddedModelField(model_container=accounts.models.Notice_Period, model_form_class=accounts.models.Notice_PeriodForm, null=True),
        ),
    ]
