# Generated by Django 2.2.9 on 2020-06-29 19:39

import accounts.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200629_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support_Craft_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vessel_Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Support_Craft_Owner', models.CharField(blank=True, max_length=1000, null=True)),
                ('Telephone', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='support_craft_details',
            field=djongo.models.fields.EmbeddedModelField(model_container=accounts.models.Support_Craft_Details, model_form_class=accounts.models.Support_Craft_DetailsForm, null=True),
        ),
    ]
