# Generated by Django 2.2.9 on 2020-06-29 19:51

import accounts.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200629_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_under_the_control_of_authorities', models.CharField(blank=True, max_length=1000, null=True)),
                ('Current_port_security_level', models.CharField(blank=True, max_length=1000, null=True)),
                ('What_is_considered_port_limits', models.CharField(blank=True, max_length=1000, null=True)),
                ('What_is_considered_international_waters', models.CharField(blank=True, max_length=1000, null=True)),
                ('Distance_from_support_base', models.CharField(blank=True, max_length=1000, null=True)),
                ('Transit_time_from_shore_to_STS_location', models.CharField(blank=True, max_length=1000, null=True)),
                ('Size_of_transfer_area', models.CharField(blank=True, max_length=1000, null=True)),
                ('Does_the_area_have_a_large_enough_run_in_area', models.CharField(blank=True, max_length=1000, null=True)),
                ('Is_the_transfer_area_sheltered', models.CharField(blank=True, max_length=1000, null=True)),
                ('Regulations_to_be_complied_during_the_operation', models.CharField(blank=True, max_length=1000, null=True)),
                ('Nature_of_seabed', models.CharField(blank=True, max_length=1000, null=True)),
                ('Average_depth_of_water', models.CharField(blank=True, max_length=1000, null=True)),
                ('STS_location_suitable_for_anchoring', models.CharField(blank=True, max_length=1000, null=True)),
                ('Any_other_service_provider_in_the_same_vicinity', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='area_details',
            field=djongo.models.fields.EmbeddedModelField(model_container=accounts.models.Area_Details, model_form_class=accounts.models.Area_DetailsForm, null=True),
        ),
    ]
