# Generated by Django 2.2.9 on 2020-06-29 19:55

import accounts.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200629_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigational_Hazards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Local_marine_activity', models.CharField(blank=True, max_length=1000, null=True)),
                ('Any_physical_limitations_on_vessel_size', models.CharField(blank=True, max_length=1000, null=True)),
                ('Distance_from_land', models.CharField(blank=True, max_length=1000, null=True)),
                ('Any_other_navigational_hazards_in_the_area', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='navigational_hazards',
            field=djongo.models.fields.EmbeddedModelField(model_container=accounts.models.Navigational_Hazards, model_form_class=accounts.models.Navigational_HazardsForm, null=True),
        ),
    ]
