# Generated by Django 2.2.9 on 2020-06-29 20:05

import accounts.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200629_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environmental_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_adjacent_to_any_public_sensitive_areas', models.CharField(blank=True, max_length=1000, null=True)),
                ('Environmental_bodies_to_be_advised_of_operations', models.CharField(blank=True, max_length=1000, null=True)),
                ('Local_oil_pollution_prevention_requirements', models.CharField(blank=True, max_length=1000, null=True)),
                ('STS_area_covered_by_oil_spill_organisation', models.CharField(blank=True, max_length=1000, null=True)),
                ('Contract_directly_with_an_Oil_pollution_contractor', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='environmental_details',
            field=djongo.models.fields.EmbeddedModelField(model_container=accounts.models.Environmental_Details, model_form_class=accounts.models.Environmental_DetailsForm, null=True),
        ),
    ]
