# Generated by Django 2.2.9 on 2020-07-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200702_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='locations_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
