# Generated by Django 2.2.9 on 2020-07-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_locations_locations_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='locations_pic',
        ),
        migrations.AddField(
            model_name='entry',
            name='locations_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
