# Generated by Django 2.2.9 on 2020-07-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_locations_locations_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='Agent_Company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='Provider_company',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
