# Generated by Django 2.2.9 on 2020-07-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200704_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
