# Generated by Django 2.2.9 on 2020-07-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_entry_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='STS_lautitude_position',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='STS_longitude_position',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
