# Generated by Django 2.2.9 on 2020-07-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200706_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='STS_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='STS_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
