# Generated by Django 2.2.9 on 2020-07-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200709_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='locations_pic',
        ),
        migrations.AddField(
            model_name='entry',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='entry',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='entry',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='entry',
            name='Image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='entry',
            name='Image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='entry',
            name='number_of_images',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
